navigation:
- text: home
  url: /index.html
- text: About
  url: /about.html
- text: releases
  url: /releases.html
- text: install
  url: /install.html
- text: maintainers
  url: /maintainers.html

maintainers:
  - text: Bruno Pagani 
  - text: Luca Boccassi 
  - text: Melroy van den Berg 
  - text: Peter Wu 
  - text: Joaquín Ignacio Aramendía
  - text: Starks
  - text: Jaron Viëtor
  - text: Vincent Cheng